
sass:
  style: expanded

google_analytics: UA-116192858-1

remote_theme: filbranden/jekyll-theme-octocopycat

octocopycat:

  sitemap:
  - title: Home
    url: /
  - title: About
    url: /about.html

  vcard:
    fullname: Filipe Brandenburger
    location: United States
    company: Google
    bio: Linux Plumber ğŸ‘¨â€ğŸ”§
    email: filbranden@gmail.com

